name: DriversF2

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: '*/15 * * * 5-6'
    - cron: '*/5 * * * 0'
  workflow_dispatch:
    
jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Check Python
        run: |
          python3 --version
          which python3

      - name: Install dependencies
        run: |
          python3 -m venv venv
          source venv/bin/activate
          python install --upgrade pip
          python install -r requirements.txt
          python -m playwright install

      - name: Run scraper
        run: |
          source venv/bin/activate
          python f2.py
